version: '2'
services:
    jhp-app:
        image: jhp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhp-mysql:3306/jhp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhp-mysql:
        extends:
            file: mysql.yml
            service: jhp-mysql
